
package uy.com.dusa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSConsultaStockService", targetNamespace = "http://ws.dusa.com.uy/", wsdlLocation = "http://dev.dusa.com.uy/ws_consulta_stock?wsdl")
public class WSConsultaStockService
    extends Service
{

    private final static URL WSCONSULTASTOCKSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTASTOCKSERVICE_EXCEPTION;
    private final static QName WSCONSULTASTOCKSERVICE_QNAME = new QName("http://ws.dusa.com.uy/", "WSConsultaStockService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev.dusa.com.uy/ws_consulta_stock?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTASTOCKSERVICE_WSDL_LOCATION = url;
        WSCONSULTASTOCKSERVICE_EXCEPTION = e;
    }

    public WSConsultaStockService() {
        super(__getWsdlLocation(), WSCONSULTASTOCKSERVICE_QNAME);
    }

    public WSConsultaStockService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTASTOCKSERVICE_QNAME, features);
    }

    public WSConsultaStockService(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTASTOCKSERVICE_QNAME);
    }

    public WSConsultaStockService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTASTOCKSERVICE_QNAME, features);
    }

    public WSConsultaStockService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSConsultaStockService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSConsultaStock
     */
    @WebEndpoint(name = "WSConsultaStockPort")
    public WSConsultaStock getWSConsultaStockPort() {
        return super.getPort(new QName("http://ws.dusa.com.uy/", "WSConsultaStockPort"), WSConsultaStock.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSConsultaStock
     */
    @WebEndpoint(name = "WSConsultaStockPort")
    public WSConsultaStock getWSConsultaStockPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dusa.com.uy/", "WSConsultaStockPort"), WSConsultaStock.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTASTOCKSERVICE_EXCEPTION!= null) {
            throw WSCONSULTASTOCKSERVICE_EXCEPTION;
        }
        return WSCONSULTASTOCKSERVICE_WSDL_LOCATION;
    }

}
