
package uy.com.dusa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSPedidos", targetNamespace = "http://ws.dusa.com.uy/")
@XmlSeeAlso({
    PedidoObjectFactory.class
})
public interface WSPedidos {


    /**
     * 
     * @param usuario
     * @param pedido
     * @param password
     * @return
     *     returns uy.com.dusa.ws.ResultRealizarPedido
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "realizarPedidoSimple", targetNamespace = "http://ws.dusa.com.uy/", className = "uy.com.dusa.ws.RealizarPedidoSimple")
    @ResponseWrapper(localName = "realizarPedidoSimpleResponse", targetNamespace = "http://ws.dusa.com.uy/", className = "uy.com.dusa.ws.RealizarPedidoSimpleResponse")
    @Action(input = "http://ws.dusa.com.uy/WSPedidos/realizarPedidoSimpleRequest", output = "http://ws.dusa.com.uy/WSPedidos/realizarPedidoSimpleResponse")
    public ResultRealizarPedido realizarPedidoSimple(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "pedido", targetNamespace = "")
        DataPedidoSimple pedido);

}
